version: "1.0"
stages:
  - "clone"
  - "test"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    stage: "clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"

  test:
    title: Executing tests
    type: freestyle
    stage: "test"
    working_directory: "${{clone}}"
    arguments:
      image: "alpine"
      commands:
        - echo "Executing tests"
        - cf_export PARAMETER_1=val

  build:
    title: "Building Docker image"
    type: "build"
    stage: "build"
    image_name: "${{CF_REPO_NAME}}"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
    dockerfile: "Dockerfile"

  jira-issue-extractor:
    title: Enrich image with annotations
    type: jira-issue-extractor
    stage: "build"
    arguments:
      IMAGE: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-dev/${{CF_REPO_NAME}}:${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
      JIRA_PROJECT_PREFIX: "SDLC"
      MESSAGE: "${{CF_BRANCH}}"
      JIRA_CONTEXT: jira

  enrich-image:
    title: Enrich image with annotations
    type: image-enricher
    stage: "build"
    arguments:
      IMAGE: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-dev/${{CF_REPO_NAME}}:${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
      BRANCH: '${{CF_BRANCH}}'
      REPO: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
      GIT_PROVIDER_NAME: github
