version: "1.0"
stages:
  - "promote"
  - "deploy"

steps:
  push:
    type: push
    stage: "promote"
    arguments:
      candidate: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-dev/${{CF_REPO_NAME}}:${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
      tag: ${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}
      image_name: "${{CF_REPO_NAME}}"
      registry: prod

  jira-issue-extractor:
    title: Enrich image with annotations
    type: jira-issue-extractor
    stage: "promote"
    arguments:
      IMAGE: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/${{CF_REPO_NAME}}:${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}"
      JIRA_PROJECT_PREFIX: "SDLC"
      MESSAGE: "${{CF_BRANCH}}"
      JIRA_CONTEXT: jira

  enrich-image:
    title: Enrich image with annotations
    type: image-enricher
    stage: "promote"
    arguments:
      IMAGE: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/${{CF_REPO_NAME}}:${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}"
      BRANCH: '${{CF_BRANCH}}'
      REPO: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
      GIT_PROVIDER_NAME: github

  clone-gitops:
    title: "Cloning GitOps repository"
    type: "git-clone"
    stage: "deploy"
    repo: "${{CF_REPO_OWNER}}/gitops"
    revision: "master"
    git: "github"

  commit:
    title: Commit to GitOps repo new version
    type: freestyle
    stage: "deploy"
    working_directory: "${{clone-gitops}}"
    arguments:
      image: "alpine/git"
      commands:
        - git status
        - "cat basic/${{CF_REPO_NAME}}/deployment.yaml"
        - "sed -i 's|image: .*|image: swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/${{CF_REPO_NAME}}:${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}-1|' basic/${{CF_REPO_NAME}}/deployment.yaml"
        - "cat basic/${{CF_REPO_NAME}}/deployment.yaml"
        - "git config --global user.email bot@huawei.com"
        - "git config --global user.email bot"
        - "git add ."
        - 'git commit -m "deploy new version ${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}"'
        - "git push https://${{GIT_USER}}:${{GIT_TOKEN}}@github.com/${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}.git"

