version: "1.0"
stages:
  - "prepare"
  - "promote"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    stage: "prepare"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"

  push:
    type: push
    stage: "promote"
    arguments:
      candidate: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-dev/${{CF_REPO_NAME}}:${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}"
      tag: ${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}
      image_name: "${{CF_REPO_NAME}}"
      registry: prod

  jira-issue-extractor:
    title: Enrich image with annotations
    type: jira-issue-extractor
    stage: "promote"
    arguments:
      IMAGE: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/${{CF_REPO_NAME}}:${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}"
      JIRA_PROJECT_PREFIX: "SDLC"
      MESSAGE: "${{CF_BRANCH}}"
      JIRA_CONTEXT: jira

  enrich-image:
    title: Enrich image with annotations
    type: image-enricher
    stage: "promote"
    arguments:
      IMAGE: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/${{CF_REPO_NAME}}:${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}"
      BRANCH: '${{CF_BRANCH}}'
      REPO: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
      GIT_PROVIDER_NAME: github

  clone-gitops:
    title: "Cloning GitOps repository"
    type: "git-clone"
    stage: "deploy"
    repo: "${{CF_REPO_OWNER}}/gitops"
    revision: "master"
    git: "github"

  test:
    title: Executing tests
    type: freestyle
    stage: "deploy"
    working_directory: "${{clone-gitops}}"
    arguments:
      image: "alpine/git"
      commands:
        - git status
        - "sed -i 's|image: .*|image: swr.tr-west-1.myhuaweicloud.com/trc-sdlc-prod/${{CF_REPO_NAME}}:${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}|' your-deployment-file.yaml"
