version: "1.0"
stages:
  - "prepare"
  - "promote"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    stage: "prepare"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH_TAG_NORMALIZED}}"
    git: "github"

  push:
    type: push
    stage: "promote"
    arguments:
      candidate: "swr.tr-west-1.myhuaweicloud.com/trc-sdlc/${{CF_REPO_NAME}}:${{CF_BRANCH_TAG_NORMALIZED}}"
      tag: ${{CF_PULL_REQUEST_TARGET}}-${{CF_SHORT_REVISION}}
      image_name: "${{CF_REPO_NAME}}"
      registry: huawei
